spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa.database-platform: org.hibernate.dialect.H2Dialect
  #Turn Statistics on
  jpa.properties.hibernate.generate_statistics: true
  # Show all queries
  jpa.show-sql: true
  jpa.properties.hibernate.format_sql: true

logging.level.org.hibernate:
  type: trace
  stat: debug
