spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

# ===========JPA Config====================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  #Turn Statistics on and Show all queries
      hibernate.generate_statistics: true
      hibernate.format_sql: true
      hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ===========Logging Config====================
logging:
  level:
    root: WARN
    com.currency: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate:
      type: trace
      stat: debug
